# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-03 22:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('prerequisitos', models.ManyToManyField(blank=True, to='herramienta.Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='InstrumentoMedicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField(choices=[(1, 'Media'), (0, 'Mediana')], default=1)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('periodo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Instrumento de medicion',
                'verbose_name_plural': 'Instrumentos de medicion',
            },
        ),
        migrations.CreateModel(
            name='medidaOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField(choices=[(1, 'Media'), (0, 'Mediana')], default=1)),
                ('periodo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='herramienta.Curso')),
            ],
            options={
                'verbose_name': 'Medida Outcome',
                'verbose_name_plural': 'Medidas Outcomes',
            },
        ),
        migrations.CreateModel(
            name='OutcomeAbet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Outcome Abet',
                'verbose_name_plural': 'Outcomes Abet',
            },
        ),
        migrations.CreateModel(
            name='PlanesDeMejora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramienta.Curso')),
            ],
            options={
                'verbose_name': 'Plan de mejora',
                'verbose_name_plural': 'Planes de mejora',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cursos', models.ManyToManyField(to='herramienta.Curso')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='medidaoutcome',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='herramienta.OutcomeAbet'),
        ),
        migrations.AddField(
            model_name='instrumentomedicion',
            name='medidaOutcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramienta.medidaOutcome'),
        ),
    ]
