# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-10 20:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='InstrumentoMedicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField()),
                ('descripcion', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeAbet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('instrumentos', models.ManyToManyField(to='herramienta.InstrumentoMedicion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanesDeMejora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cursos', models.ManyToManyField(to='herramienta.Curso')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='instrumentos',
            field=models.ManyToManyField(to='herramienta.InstrumentoMedicion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='outcomes',
            field=models.ManyToManyField(to='herramienta.OutcomeAbet'),
        ),
        migrations.AddField(
            model_name='curso',
            name='planes',
            field=models.ManyToManyField(to='herramienta.PlanesDeMejora'),
        ),
    ]
