# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-04 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentomedicion',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='outcomeabet',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
