# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-10 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Profesor',
        ),
    ]
