# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0002_auto_20190604_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisIntercurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('periodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medidaoutcome',
            name='tipo',
            field=models.BooleanField(choices=[(1, 'Media'), (0, 'Mediana')]),
        ),
        migrations.AddField(
            model_name='analisisintercurso',
            name='curso1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis1', to='herramienta.Curso'),
        ),
        migrations.AddField(
            model_name='analisisintercurso',
            name='curso2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis2', to='herramienta.Curso'),
        ),
        migrations.AddField(
            model_name='analisisintercurso',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='herramienta.OutcomeAbet'),
        ),
    ]
