# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-10 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0002_auto_20190510_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='instrumentos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='planes',
        ),
        migrations.RemoveField(
            model_name='outcomeabet',
            name='instrumentos',
        ),
        migrations.AddField(
            model_name='instrumentomedicion',
            name='curso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='herramienta.Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentomedicion',
            name='outcome',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='herramienta.OutcomeAbet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planesdemejora',
            name='curso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='herramienta.Curso'),
            preserve_default=False,
        ),
    ]
