# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0003_auto_20190510_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentomedicion',
            options={'verbose_name': 'Instrumento de medicion', 'verbose_name_plural': 'Instrumentos de medicion'},
        ),
        migrations.AlterModelOptions(
            name='outcomeabet',
            options={'verbose_name': 'Outcome Abet', 'verbose_name_plural': 'Outcomes Abet'},
        ),
        migrations.AlterModelOptions(
            name='planesdemejora',
            options={'verbose_name': 'Plan de mejora', 'verbose_name_plural': 'Planes de mejora'},
        ),
        migrations.AddField(
            model_name='curso',
            name='prerequisitos',
            field=models.ManyToManyField(to='herramienta.Curso'),
        ),
    ]
