# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0003_auto_20190612_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombreCorto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
