# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0004_auto_20190512_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='prerequisitos',
            field=models.ManyToManyField(blank=True, to='herramienta.Curso'),
        ),
    ]
