# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-20 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0006_auto_20190520_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidaoutcome',
            options={'verbose_name': 'Medida Outcome', 'verbose_name_plural': 'Medidas Outcomes'},
        ),
        migrations.AddField(
            model_name='medidaoutcome',
            name='tipo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
