# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-25 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0007_auto_20190520_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentomedicion',
            name='tipo',
            field=models.BooleanField(choices=[(1, 'Media'), (0, 'Mediana')], default=1),
        ),
        migrations.AlterField(
            model_name='medidaoutcome',
            name='tipo',
            field=models.BooleanField(choices=[(1, 'Media'), (0, 'Mediana')], default=1),
        ),
    ]
