# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-03 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0008_auto_20190525_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='outcomes',
        ),
        migrations.AlterField(
            model_name='medidaoutcome',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='herramienta.Curso'),
        ),
        migrations.AlterField(
            model_name='medidaoutcome',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='herramienta.OutcomeAbet'),
        ),
    ]
